In [2]:
import numpy as np
a=np.array([[1,4,3],[5,8,7]])
print("Array created using Passed List:\n",a)

Array created using Passed List:
 [[1 4 3]
 [5 8 7]]


In [6]:
b=np.zeros([3,4])
print("\n Array initialized with all zeros\n",b)


 Array initialized with all zeros
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
c=np.full((3,3),6)
print("\n Array initialized with all 6 \n",c)


 Array initialized with all 6 
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [10]:
d=np.random.random((2,2))
print("\n A random array:\n",d)


 A random array:
 [[0.58238345 0.44911435]
 [0.04861372 0.92260691]]


In [14]:
e=np.arange(0,30,5)
print("\n A sequential array with step of 5:\n",e)


 A sequential array with step of 5:
 [ 0  5 10 15 20 25]


In [15]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
reshaped_arr=arr.reshape(4,3)
print(arr)
print(reshaped_arr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [16]:
fl_arr=arr.flatten()
print(arr)
print(fl_arr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[1 2 3 4 5 2 4 2 1 2 0 1]


In [17]:
print(arr.ndim)


2


In [18]:
print(arr.shape)

(3, 4)


In [19]:
print(arr.size)

12


In [20]:
print(arr.dtype)

int64


In [21]:
c=arr.astype("f")
print(c)
b=arr.astype("i")
print(b)

[[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]


In [22]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2:2])

[]


In [23]:
print(p[3:3])

[]


In [24]:
c=p.astype('i')
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
