In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
print("Original array:",arr)
x = np.where(arr == 4)
print("\nIndexes where the value is 4:\n",x)

Original array: [1 2 3 4 5 4 4]

Indexes where the value is 4:
 (array([3, 5, 6], dtype=int64),)


In [7]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7.8])
x = np.where(arr%2 == 0)
print("\nOriginal array:",arr)
print("\nIndexes where the values are even:",x)


Original array: [1.  2.  3.  4.  5.  6.  7.8]

Indexes where the values are even: (array([1, 3, 5], dtype=int64),)


In [9]:
#indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8])
x = np. where (arr%2 == 0)
print("\nOriginal array:",arr)
print("\nIndexes where the values are even:",x)


Original array: [1 2 3 4 5 6 7 8]

Indexes where the values are even: (array([1, 3, 5, 7], dtype=int64),)


In [14]:
#indexes where the value 3 should be serted erted starting from the right
x = np.searchsorted (arr, 3, side='left') 
print("\nindexes where the value 3 should be inserted, starting from the right:",x)


indexes where the value 3 should be inserted, starting from the right: 2


In [17]:
arr= np.array([3, 2, 0, 1])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))
arr = np.array([[3, 2, 4], [5, 0, 1]])
print("\nOriginal array:",arr)
print("\nSorted array:", np.sort(arr))


Original array: [3 2 0 1]

Sorted array: [0 1 2 3]

Original array: [[3 2 4]
 [5 0 1]]

Sorted array: [[2 3 4]
 [0 1 5]]


In [18]:
#Filter
arr = np.array([41, 42, 43, 44])
x= [True, False, True, False]
newarr = arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x) 
print("\nFilter array:", newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [23]:
arr = np.array([41, 42, 43, 44])
filter_arr=arr > 42
newarr = arr[filter_arr]
print("\nOriginal array:",arr) 
print("\nFilter array:condition->42:",filter_arr)
print("\nNew array:", newarr)


Original array: [41 42 43 44]

Filter array:condition->42: [False False  True  True]

New array: [43 44]
