In [1]:
import numpy as np
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])
print("Original array:\n", arr)

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [3]:
print("\nEvery other rows: \n", arr[0:3:2])


Every other rows: 
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [8]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("\nOriginal array:",arr)
print("\nReturns every other elements in the array:arr[::2]:",arr[::2])


Original array: [1 2 3 4 5 6 7]

Returns every other elements in the array:arr[::2]: [1 3 5 7]


In [14]:
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])

temp = arr[:2,:3]
print ("\nArray with first 2 rows and 3 columns:\n", temp)


Array with first 2 rows and 3 columns:
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [7]:
import numpy as np
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])

cond = arr > 2
temp = arr[cond]
print ("\nElements greater than 2:\n", temp)


Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [12]:
import numpy as np
arr1= np.array([1, 2, 3])
arr2= np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print("\nOriginal arrays:\n",arr1, arr2)
print("\nJoined array:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [14]:
arr3=np.hstack((arr1, arr2))
print("\nHorizondal joining:\n",arr)


Horizondal joining:
 [1 2 3 4 5 6]


In [15]:
arr4=np.vstack((arr1,arr2))
print("\nVertical joining:\n",arr4)


Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [16]:
arr5=np.dstack((arr1,arr2))
print("\nDepth joining:\n:",arr5)


Depth joining:
: [[[1 4]
  [2 5]
  [3 6]]]


In [18]:
arr=np.array([1,2,3,4,5,])
arr6=np.array_split(arr,3)
print(arr)
print(arr6)
print(arr6[0])
print(arr6[1])
print(arr6[2])

[1 2 3 4 5]
[array([1, 2]), array([3, 4]), array([5])]
[1 2]
[3 4]
[5]


In [21]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

apple = arr[[0,1,2,3], [3,2,1,0]]

print("\nElements at indices (0,3), (1,2), (2,1), (3,0):\n", apple)



Elements at indices (0,3), (1,2), (2,1), (3,0):
 [ 4  7 10 13]
